[package]
name = "lebu"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
portable-pty = "0.9.0"
tokio = { version = "1.48.0", features = ["full"] }
vte = "0.15.0"
